export { default as Home } from './Home.vue'
export { default as Login } from './Login.vue'
export { default as Register } from './Register.vue'
export { default as NotFound } from './NotFound.vue'
export { default as Dashboard } from './Dashboard.vue'
